### PR TITLE
Fix unsupported Intl.ListFormat

### LINKED ISSUE #4037: TypeError: undefined is not a constructor (evaluating 'new Intl.ListFormat(e,{type:this.andFilter?"conjuncti...
Sentry Issue: [ECAMP3-FRONTEND-172](https://ecamp.sentry.io/issues/4584757959/?referrer=github_integration)

```
TypeError: undefined is not a constructor (evaluating 'new Intl.ListFormat(e,{type:this.andFilter?"conjunction":"disjunction"})')
  at _sfc_main.computed.labelValue (../src/components/dashboard/SelectFilter.vue:81:1)
  at fn (../src/components/dashboard/SelectFilter.vue:122:1)
...
(12 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by manuelmeister**
Fixes #4037

### CODE REVIEW

File: frontend/src/components/dashboard/SelectFilter.vue [hunk 1]
```diff
@@ -78,10 +78,14 @@ export default {
...
-        })
-        return listFormat.format(list)
+        if ('Intl' in window && 'ListFormat' in Intl) {
+          const listFormat = new Intl.ListFormat(lang, {
+            type: this.andFilter ? 'conjunction' : 'disjunction',
+          })
+          return listFormat.format(list)
+        } else {
+          return list.join(', ')
+        }
```
Comment (BacLuc) [inline frontend/src/components/dashboard/SelectFilter.vue]: minor: you don't need the else

**Review by BacLuc — APPROVED** [review]

**Review by carlobeltrame — APPROVED** [review]
We have to remember to do this whereever we use the intl api

**Comment by manuelmeister** [comment]
@carlobeltrame I would solve this on a per opened sentry issue basis, as I think it is not our goal to make it fully supported in unsupported browsers.
