### PR TITLE
fix(frontend): fix and simplify picasso drag-and-drop

### LINKED ISSUE #3463: Drag and drop bug on picasso
When dragging new schedule entries onto the picasso, under some yet unknown conditions, sometimes the release is not triggered, and the gray placeholder schedule entry gets stuck to the mouse pointer permanently:

[Bildschirmaufzeichnung vom 2023-05-15, 22-30-03 (getrimmt).webm](https://github.com/ecamp/ecamp3/assets/7566995/4b6bef4a-af7a-492a-867f-78067ddbedf9)

The bug has several, progressively worse stages. Timeline of the above video:
0:03 - 0:11 stage 1
0:12 - 0:32 stage 2
0:33 - 0:44 back in stage 1
0:44 user refreshes the page to get rid of the bug
(Stage 3 is never reached in this video, see below for a video of that)

### Stage 1: Canceling the dialog
I was able to reproduce this by double-clicking on the draggable picasso surface, while moving the mouse pointer enough in vertical direction between the two clicks. It has to be at least enough movement such that a minimal length schedule entry is created (i.e. **in very short succession: click, drag a little bit, click**):
[picasso-dragging-bug-1.webm](https://github.com/ecamp/ecamp3/assets/7566995/88c968b6-f131-4eaa-9171-8a223ac9f092)

### Stage 2: Getting the schedule entry end stuck to the cursor
Once a user is in stage 1, they might try to get rid of the gray placeholder and/or re-trigger the dialog, by dragging the length handle of the placeholder. This makes matters worse, because now, the end of the schedule entry is stuck to the mouse cursor, until the user clicks again, getting back to stage 1.
In some cases, we can also get directly to stage 2, when the second click of the reproduction above accidentally grabs and moves the length handle of the placeholder schedule entry.
[picasso-dragging-bug-2.webm](https://github.com/ecamp/ecamp3/assets/7566995/b669daa0-e703-4a5c-8553-8370d8b1e350)

### Stage 3: Getting the entire schedule entry stuck to the cursor
While in stage 1, if the user tries to move the placeholder schedule entry by dragging its body, the placeholder gets stuck permanently to the mouse cursor. I have found no way to get out of this situation, except for refreshing the page. In this stage, if the user tries to save the schedule entry, we get a console error `g._meta is undefined` or `Cannot read properties of undefined (reading 'self')` or `undefined is not an object (evaluating 'g._meta.self')` in the ScheduleEntries.vue component. These are collected in a [Sentry issue](https://ecamp.sentry.io/issues/4004671918/?project=5602507).
[picasso-dragging-bug-3.webm](https://github.com/ecamp/ecamp3/assets/7566995/59648ba8-4b8a-46ec-b019-b3b9eceabc06)

### PR DESCRIPTION
**Pull request by usu**
Supersedes #3467 

Fixes https://github.com/ecamp/ecamp3/issues/3463 (hopefully)
also adresses https://github.com/ecamp/ecamp3/pull/3410#pullrequestreview-1384144228

The first commit is cherry-picked from #3467 and fixes the bug.

The other commits only simplify and cleanup the code with no major change in functionality, with one exception: I changed the resize operation to disallow negative changes (resizing upwards of the original start time). This makes the code simpler, gives the resize operation a single responsibility (I cannot misuse resize to move an event) and is consistent with other calendars such as Google Calendar.

All operations now use `roundTimeToNearestQuarterHour` with the exception of resize which still uses `roundTimeUpToNextQuarterHour`.  To me this felt more natural to use, because the resize handler is a bit higher up (lower in timestamp) than the border of the event. 

A cosmetic open issue is the display of cursor animations and event hover animations, which is not always consistent during drag & drop. I didn't want to touch on this, because this needs messing with the same CSS, that was already touched by #3411.

### CODE REVIEW

**Review by carlobeltrame — APPROVED** [review]
Can't test right now, don't have a computer until Sunday. But code LGTM, thanks for cleaning up!

File: frontend/src/helpers/vCalendarDragAndDrop.js [hunk 1]
```diff
@@ -2,35 +2,29 @@
  * helpers for VCalendar DragAndDrop composables
  */
 
+const ONE_MINUTE = 60 * 1000
+const ONE_HOUR = 60 * ONE_MINUTE
+const ONE_DAY = 24 * ONE_HOUR
+const QUARTER_HOUR = 15 * ONE_MINUTE
```
Comment (BacLuc) [inline frontend/src/helpers/vCalendarDragAndDrop.js]:
```suggestion
const MILLIS_FOR_ONE_MINUTE = 60 * 1000
const MILLIS_FOR_ONE_HOUR = 60 * ONE_MINUTE
const MILLIS_FOR_ONE_DAY = 24 * ONE_HOUR
const MILLIS_FOR_QUARTER_HOUR = 15 * ONE_MINUTE
```

File: frontend/src/helpers/vCalendarDragAndDrop.js [hunk 2]
```diff
@@ -2,35 +2,29 @@
...
+  return Math.round(time / QUARTER_HOUR) * QUARTER_HOUR
 }
 
-const roundTimeUp = (time) => {
-  const roundTo = 15 // minutes
-  const roundDownTime = roundTo * 60 * 1000
-
-  return time + (roundDownTime - (time % roundDownTime))
+const roundTimeUpToNextQuarterHour = (time) => {
+  return time + (QUARTER_HOUR - (time % QUARTER_HOUR))
```
Comment (BacLuc) [inline frontend/src/helpers/vCalendarDragAndDrop.js]:
```suggestion
  return Math.ceil(time / QUARTER_HOUR) * QUARTER_HOUR
```

**Review by BacLuc — COMMENTED** [review]
It works, thank you very much.
What do we do now with #3410 ?

File: frontend/src/helpers/vCalendarDragAndDrop.js (hunk 1 above)
Comment (usu) [reply frontend/src/helpers/vCalendarDragAndDrop.js]: https://github.com/ecamp/ecamp3/pull/3468/commits/b06914ea095b1854436a94b709ae412462c4ca3b

File: frontend/src/helpers/vCalendarDragAndDrop.js (hunk 2 above)
Comment (usu) [reply frontend/src/helpers/vCalendarDragAndDrop.js]: https://github.com/ecamp/ecamp3/pull/3468/commits/b06914ea095b1854436a94b709ae412462c4ca3b

**Comment by usu** [comment]
> What do we do now with #3410 ?

#3410 is superseded by this PR. Will close it.

**Review by BacLuc — APPROVED** [review]
