### PR TITLE
Fix SideBarProgram in Activity view

### LINKED ISSUE #8492: Readd SidebarProgram
In https://github.com/ecamp/ecamp3/commit/e75c920a334cb035d1cea864c3570c5e52cc6505 @BacLuc removed the SidebarProgram during
the migration to vue3.
- https://github.com/ecamp/ecamp3/issues/8271

Now we want to add this again.
See the changes necessary for CampProgram.

### PR DESCRIPTION
**Pull request by manuelmeister**
Fixes #8492

### CODE REVIEW

**Review by BacLuc — APPROVED** [review]
Thank you, very cool

File: frontend/src/components/activity/DaySwitcher.vue [hunk 1]
```diff
@@ -128,17 +143,31 @@ export default {
 .basis-num {
   width: 2.5ch;
 }
-
 /* .e-day-switcher__menu is in the <e-select> tag */
 /*noinspection CssUnusedSymbol*/
-.e-day-switcher__menu {
+.ec-day-switcher__menu {
```
Comment (simfeld) [inline frontend/src/components/activity/DaySwitcher.vue:148]: change comment above too?

**Review by simfeld — APPROVED** [review]
