### PR TITLE
fix(api+frontend): verify that user is activated during authentication

### LINKED ISSUE #2020: Security, implement User.State
https://github.com/ecamp/ecamp3/pull/2003#discussion_r720737536

### PR DESCRIPTION
**Pull request by usu**
From epic #1237:

> User state beachten bei Login: Aktiviert?

Error message shown in frontend is currently untranslated. Should be implemented after merging #2953

image

Fixes #2020

### CODE REVIEW

File: api/tests/DataPersister/Util/DataPersisterObservableTest.php [hunk 1]
```diff
@@ -154,10 +154,10 @@ public function testCallCustomActionListenersForItemOperation() {
         $this->dataPersisterObservable->persist($toPersist, ['item_operation_name' => self::ACTION_NAME]);
     }
 
-    public function testCallCustomActionListenersForItemOperationTwiceIfRegisteredTwice() {
+    public function testCallCustomActionListenersForItemOperationOnlyOnceIfRegisteredTwice() {
```
Comment (BacLuc) [inline api/tests/DataPersister/Util/DataPersisterObservableTest.php:157]: Okay, we share the DataPersisterObservable between two requests?

**Review by BacLuc — APPROVED** [review]

File: api/tests/DataPersister/Util/DataPersisterObservableTest.php (hunk 1 above)
Comment (usu) [reply api/tests/DataPersister/Util/DataPersisterObservableTest.php:157]: Yes, in the tests when reboot is enabled with:
```
$client->disableReboot();
```

**Review by simfeld — APPROVED** [review]
