### PR TITLE
Fix error messages not visible in activity view

### LINKED ISSUE #4267: Error messages on content node contents are sometimes hidden
grafik

But also not on dev:
grafik

but this is broken on staging (and i assume on prod) too
grafik

_Originally posted by @BacLuc in https://github.com/ecamp/ecamp3/issues/4264#issuecomment-1862977537_

### PR DESCRIPTION
**Pull request by manuelmeister**
Fixes #4267

### CODE REVIEW

**Comment by BacLuc** [comment]
failed because of coveralls.
see https://github.com/ecamp/ecamp3/pull/4131

**Review by pmattmann — APPROVED** [review]

File: frontend/src/components/activity/content/SafetyConcept.vue [hunk 1]
```diff
@@ -7,7 +7,7 @@
       rows="2"
       :disabled="layoutMode || disabled"
       :filled="layoutMode"
-      height="100%"
+      class="grow-v-slot"
```
Comment (usu) [inline frontend/src/components/activity/content/SafetyConcept.vue:10]: Sometimes you use `class=`, sometimes you use `input-class=`.
Seems both do the job, but might be better to be consistent. No?

Comment (manuelmeister) [reply frontend/src/components/activity/content/SafetyConcept.vue:10]: Thanks good point.

**Review by usu — APPROVED** [review]
