### PR TITLE
pdf: fix NPE for empty <li> tags in RichText.vue

### LINKED ISSUE #3759: Print Layout #2 breaks with empty bullet list items
In Activity https://dev.ecamp3.ch/camps/6973c230d6b1/Harry-Potter-Lager/program/activities/27bceddd3308

There is a text formatting with empty bullet points.
grafik

If you click on print activity with Layout # 2, the formatted text is not printed due to an error you also see in the console.
[Beginn-und-Anreise(4).pdf](https://github.com/ecamp/ecamp3/files/12590149/Beginn-und-Anreise.4.pdf)

The code for PDF Layout # 2 is located in the pdf directory of the ecamp3 repository.
The error probably happens somewhere in the [code for rendering lists in rich text fields](https://github.com/ecamp/ecamp3/blob/devel/pdf/src/campPrint/RichText.vue#L66..L86).

Goal:
There is no error in the console, and the formatted text is printed as expected.

### PR DESCRIPTION
**Pull request by BacLuc**
closes #3759

### CODE REVIEW

**Review by usu — APPROVED** [review]

**Comment by BacLuc** [comment]
@carlobeltrame maybe you could help me out quickly.
Why would our custom vue renderer switch between margin and padding between (container, local) and CI?
https://github.com/ecamp/ecamp3/actions/runs/6358702977/job/17271233273?pr=3868

**Comment by BacLuc** [comment]
Thank you, rebasing

**Comment by BacLuc** [comment]
thank you, rebasing worked

File: pdf/src/campPrint/RichText.vue [hunk 1]
```diff
@@ -70,6 +70,23 @@ const rules = [
...
+        attrs: {},
+        children: [],
+        content: '',
+      }
+      if (!node.children.length) {
+        node.children.push({
+          type: 'text',
+          attrs: {},
+          children: [childWithEmptyText],
+        })
```
Comment (carlobeltrame) [inline pdf/src/campPrint/RichText.vue]: Can't you simplify this?
```suggestion
        node.children.push(childWithEmptyText)
```
The additional child will be added afterwards anyways.

File: pdf/src/campPrint/RichText.vue [hunk 2]
```diff
@@ -70,6 +70,23 @@ const rules = [
   {
     shouldProcessNode: (node) => node.type === 'tag' && node.name === 'li',
     processNode: (node, parent) => {
+      const childWithEmptyText = {
+        type: 'text',
+        name: '',
+        attrs: {},
+        children: [],
+        content: '',
```
Comment (carlobeltrame) [inline pdf/src/campPrint/RichText.vue]: Are all of these attributes really needed? I'm not sure whether `name` is even a legal attribute, and I thought a `content` was only used in `type: 'text_instance'` nodes, but not sure...

**Review by carlobeltrame — CHANGES_REQUESTED** [review]

File: pdf/src/campPrint/RichText.vue (hunk 1 above)
Comment (BacLuc) [reply pdf/src/campPrint/RichText.vue:85]: node.children[0] also needs a child, so no

File: pdf/src/campPrint/RichText.vue (hunk 2 above)
Comment (BacLuc) [reply pdf/src/campPrint/RichText.vue]: name is checked above, for the text node it is not checked.
So i explicitly set the name to empty.
but i also can leave it out.

File: pdf/src/campPrint/RichText.vue (hunk 1 above)
Comment (BacLuc) [reply pdf/src/campPrint/RichText.vue]: then both have an empty content.
I just needed to catch both cases: a node with no children, and a node with a child without children.
I did not dive too much into the docs, i just printf'ed what happens when a empty \<li\> appears, and then put that into the implementation

File: pdf/src/campPrint/RichText.vue [hunk 3]
```diff
@@ -70,6 +70,23 @@ const rules = [
...
+      if (!node.children.length) {
+        node.children.push({
+          type: 'text',
+          attrs: {},
+          children: [childWithEmptyText],
+        })
+      }
+      if (!node.children[0].children.length) {
+        node.children[0].children.push(childWithEmptyText)
+      }
```
Comment (carlobeltrame) [inline pdf/src/campPrint/RichText.vue]: My proposal to make it more readable (untested):
```suggestion
      const emptyChild = {
        type: 'text',
        attrs: {},
        children: [],
      }
      if (!node.children.length) {
        node.children.push({ ...emptyChild })
      }
      if (!node.children[0].children.length) {
        node.children[0].children.push({ ...emptyChild, content: '' })
      }
```

File: pdf/src/campPrint/RichText.vue (hunk 1 above)
Comment (BacLuc) [reply pdf/src/campPrint/RichText.vue]: done

File: pdf/src/campPrint/RichText.vue (hunk 2 above)
Comment (BacLuc) [reply pdf/src/campPrint/RichText.vue]: done

**Comment by BacLuc** [comment]
done

**Review by carlobeltrame — APPROVED** [review]
