### PR TITLE
fix(api+frontend): ensure storyboard has min. 1 section

### LINKED ISSUE #2933: ContentNode Storyboard: dialog to ask for confirmation before deletion of a section
Currently section is immediately removed after clicking the delete button

_Originally posted by @carlobeltrame in https://github.com/ecamp/ecamp3/pull/2825#discussion_r955205061_

### LINKED ISSUE #2969: Json data: verify handling of empty objects
Storyboard sections currently have the following json format (both in DB and in api response).
```json
{
  "data": {
    "sections": {
      "2736647e-cebd-4d1d-8447-80080d8740a3": {
        "column1": "<p>1.00</p>",
        "column2": "<p>Section1</p>",
        "column3": null,
        "position": 1
      },
      "34b6f7f9-fbc6-41c4-bb26-037ce38f8143": {
        "column1": "<p>00.00</p>",
        "column2": "<p>Section2</p>",
        "column3": null,
        "position": 0
      }
    }
  }
}
```

When there's no section, the format in DB looks like this (empty object):
```json
{
  "data": {
    "sections": {}
  }
}
```

The response from API however looks like this (empty array):
```json
{
  "data": {
    "sections": []
  }
}
```

Didn't dig into this further so far, but probably this is the limitation of how PHP handles both formats as arrays (one as associative array and one as lists). When it's empty, they cannot be distinguished.

A potential solution could be to avoid usage of empty object and setting null values instead:
```json
{
  "data": {
    "sections": null
  }
}
```

### PR DESCRIPTION
**Pull request by usu**
Based on #2971

Show relevant diff only: https://github.com/ecamp/ecamp3/pull/2995/files/033f8f3a039f8f99a818a9a0d7c6faaeb4aecfcd..8262ae47a82ece54b897914472c8940e7add9d05

Fixes #2969 

Fixes #2933 

### Only 1 section, delete button disabled
image

### More than 1 section, dialog before section is removed
image

### CODE REVIEW

File: api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php [hunk 1]
```diff
@@ -43,12 +44,11 @@ public function testCreateStoryboardAcceptsValidJson() {
...
-        $this->create($this->getExampleWritePayload(['data' => null]));
+        $response = $this->create($this->getExampleWritePayload(['data' => null]));
 
         $this->assertResponseStatusCodeSame(201);
-        $this->assertJsonContains(['data' => [
-            'sections' => [],
-        ]]);
+
+        $this->assertCount(1, $response->toArray()['data']['sections']); // populated with 1 default section
     }
```
Comment (BacLuc) [inline api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php:53]: This test fails now when you don't add the content as default of the field:

    public function testCreateStoryboardAcceptsNotExistingJson() {
        $response = $this->create($this->getExampleWritePayload([], ['data']));

        $this->assertResponseStatusCodeSame(201);

        $this->assertCount(1, $response->toArray()['data']['sections']); // populated with 1 default section
    }

Maybe set the value in the constructor of StoryBoard?

**Review by BacLuc — CHANGES_REQUESTED** [review]
Creating a new StoryBoard is now not possible.
But you will fix that fast.

File: api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php (hunk 1 above)
Comment (usu) [reply api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php:53]: Ah good catch. Constructor doesn't work (tried before), because in the constructor I don't know if the `$data` property will be populated later. That's why I put the default value into `setData`. Didn't recognize that `setData` is not called at all though if the property doesn't even exist in the payload.

Was anyway an odd design decision, so moved the default fallback now back into the data persister where it also should be.

Fixed with https://github.com/ecamp/ecamp3/pull/2995/commits/0f70e5861572b7fd29ca50b2ba531636c89030e5

Comment (carlobeltrame) [reply api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php:53]: We have a similar case in the relation Camp -> Periods, where a camp always must have at least one period. How is this problem solved there?

**Review by BacLuc — APPROVED** [review]

File: api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php (hunk 1 above)
Comment (BacLuc) [reply api/tests/Api/ContentNodes/Storyboard/CreateStoryboardTest.php:53]: There we enforce that the create payload contains a Period.
testCreateCampValidatesMissingPeriods

File: api/src/Validator/AssertJsonSchemaValidator.php [hunk 2]
```diff
@@ -15,6 +15,10 @@ public function validate($value, Constraint $constraint) {
             throw new UnexpectedTypeException($constraint, AssertJsonSchema::class);
         }
 
+        if (null === $value) {
```
Comment (pmattmann) [inline api/src/Validator/AssertJsonSchemaValidator.php:18]: Wieso ist ```$value === null``` automatisch ok?

**Review by pmattmann — APPROVED** [review]

File: api/src/Validator/AssertJsonSchemaValidator.php (hunk 2 above)
Comment (usu) [reply api/src/Validator/AssertJsonSchemaValidator.php:18]: Ist ein Konzept was Symfony bei den eigenen Validators auch so einsetzt: `null`-Wert wird normalerweise als ok angesehen (bzw. vom Validator nicht überprüft) und man steuert separat via `Assert\IsNull` oder `Assert\NotNull`, wenn man null-Wert explizit vermeiden oder erzwingen will.

So is es nun möglich, dass wir null-Werte beim Erstellen erlauben, und in diesem Fall im DataPersister mit einem Default-Wert befüllen.
