### PR TITLE
Add dev data to reproduce bug #3430

### LINKED ISSUE #3430: Bugs in Picasso
In certain situations, not all blocks are shown in picasso: (Here: 3 blocks at the same time)
grafik

Or here ( a short block):
grafik

### PR DESCRIPTION
**Pull request by BacLuc**
releated to #3430

Should only be merged after https://github.com/ecamp/ecamp3/pull/3435

### CODE REVIEW

File: common/helpers/campCollaborationDisplayName.js [hunk 1]
```diff
@@ -14,7 +14,8 @@ export default function (campCollaboration, tc, indicateInactive = true) {
       : campCollaboration.inviteEmail || ''
 
   if (campCollaboration.status === 'inactive' && indicateInactive) {
-    text += ' (' + tc('entity.campCollaboration.inactive') + ')'
+    const inactiveIndicator = tc ? tc('entity.campCollaboration.inactive') : 'inactive'
```
Comment (pmattmann) [inline common/helpers/campCollaborationDisplayName.js]: This prevents the exception, but allows an invalid usage of this method. So it hides errors. 
Rather, I would throw an explanatory exception.

#3435  should cover all incorrect usages.

Comment (BacLuc) [reply common/helpers/campCollaborationDisplayName.js]: If you can assure me that all current and future usages will use this function correctly, then i am with you. (I think you can't).
Sadly v-calendar swallows the NPE which happened here completely in production and we have no sentry event which indicates that something went wrong. This would also swallow any error i throw here. (In dev you see the error in the console).

Very important to me is the change in dev data.

I would also rather have a bad default than not appearing ScheduleEntries in prod.
I would offer to add a console.error here and test that this appears in sentry?

And for the future we can think of a design that screams at the developer if he uses the function wrong.

Comment (carlobeltrame) [reply common/helpers/campCollaborationDisplayName.js]: How about we create two separate functions, one which renders the inactive state and requires the tc argument, and one which ignores the inactive state and does not accept a tc argument?

Comment (usu) [reply common/helpers/campCollaborationDisplayName.js]: > I would offer to add a console.error here and test that this appears in sentry?

I'd vote for this. Otherwise we will not detect such cases and we might generate other issues elsewhere.

This is a good example where Typescript would/will generate some value, if we ever introduce in future. It would force you to always pass the `tc` parameter.

Comment (BacLuc) [reply common/helpers/campCollaborationDisplayName.js]: I moved this to a separate issue #3437.
We can merge the changes in the dev data, so the chance increases that developers see this regression if we add it again.

**Review by pmattmann — APPROVED** [review]

**Review by carlobeltrame — APPROVED** [review]
