### PR TITLE
frontend: fix mobile view of materialLists

### LINKED ISSUE #3899: Error: slugify: string argument expected
Sentry Issue: [ECAMP3-FRONTEND-15N](https://ecamp.sentry.io/issues/4516004076/?referrer=github_integration)

```
Error: slugify: string argument expected
  at materialListRoute (../src/router.js:494:45)
  at a.O (../src/views/camp/navigation/desktop/NavTopbar.vue:84:1)
...
(5 additional frame(s) were not displayed)
```

grafik

### PR DESCRIPTION
**Pull request by BacLuc**
Fixes #3899
Navigate to the list of materiallists in the NavBottombar. Add new view for the list of materiallists
to navigate to the details of one materiallist.
Rename the views/admin/(,Admin)MaterialLists component to avoid name clash with the new component.
Add quick way to differentiate the target routes in the materialListRoute helper for the NavBottombar and NavTopbar.
May have been introduced in #3841.

Also add guard if camp is not loaded to materialListRoute.

### CODE REVIEW

File: frontend/src/router.js [hunk 1]
```diff
@@ -262,6 +262,21 @@ export default new Router({
         }),
       },
     },
+    {
+      name: 'material/lists',
```
Comment (carlobeltrame) [inline frontend/src/router.js]:
```suggestion
      name: 'material/lists', // Only used on mobile
```

File: frontend/src/views/admin/AdminMaterialLists.vue [hunk 2]
```diff
@@ -3,7 +3,7 @@ Show all material lists for a camp on mobile
 -->
```
Comment (carlobeltrame) [inline frontend/src/views/admin/AdminMaterialLists.vue:3]: Update or delete the comment on the line above this

File: frontend/src/views/material/MaterialLists.vue [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+  <content-card :title="$tc('views.material.materialLists.title')" toolbar>
+    <template v-if="!isGuest" #title-actions>
+      <DialogMaterialListCreate :camp="camp()">
+        <template #activator="{ on }">
+          <ButtonAdd class="mr-n2" height="32" v-on="on"
+            >{{ $tc('global.button.create') }}
+          </ButtonAdd>
+        </template>
+      </DialogMaterialListCreate>
+    </template>
```
Comment (carlobeltrame) [inline frontend/src/views/material/MaterialLists.vue:15]: So you actively decided to keep this button in this view?

**Review by carlobeltrame — APPROVED** [review]

File: frontend/src/views/material/MaterialLists.vue (hunk 3 above)
Comment (manuelmeister) [reply frontend/src/views/material/MaterialLists.vue:15]: I think this makes sense

File: frontend/src/router.js [hunk 4]
```diff
@@ -262,6 +262,21 @@ export default new Router({
...
+        default: () => import('./views/material/MaterialLists.vue'),
+      },
+      beforeEnter: all([requireAuth, requireCamp]),
+      props: {
+        navigation: (route) => ({ camp: campFromRoute(route) }),
+        default: (route) => ({
+          camp: campFromRoute(route),
+        }),
+      },
+    },
```
Comment (manuelmeister) [inline frontend/src/router.js:279]: I think `material/lists` should move to the camp route object as a child. (But not `material/all` as it needs the sidebar.

File: frontend/src/router.js [hunk 5]
```diff
@@ -518,25 +533,26 @@ export function campRoute(camp, subroute = 'dashboard', query = {}) {
...
+export function materialListRoute(camp, materialListOrRoute = '/all', query = {}) {
+  if (camp._meta.loading) return {}
+  if (typeof materialListOrRoute === 'string') {
     return {
-      name: 'material/overview',
+      name: `material${materialListOrRoute}`,
       params: { campId: camp.id, campTitle: slugify(camp.title) },
       query,
     }
   }
```
Comment (manuelmeister) [inline frontend/src/router.js:547]: `/all` and `/lists` should probably move to campRoute and have a route name prefix "camp/material/$1"

**Review by manuelmeister — APPROVED** [review]
Thanks for the fix. I think my change requests can be done in the followup issue #3997
