### PR TITLE
api: set report_fields_where_declared:true in doctrine.yaml for doctr…

### LINKED ISSUE #3740: Migrate data property of ContentNode and child classes to support Doctrine ORM 3.0
https://github.com/doctrine/orm/pull/10455

If we activate this switch, the api service fails to start because the
public data property of ContentNode is overridden in the children.
See https://github.com/BacLuc/ecamp3/tree/report_fields_where_declared

Idea:
Use setters for the additional validation, and getters for the api_platform openapi documentation
but don't redeclare the doctrine orm column $data

### PR DESCRIPTION
**Pull request by BacLuc**
…ine/orm 3

And don't overwrite the doctrine definition for the same field again with the same values.
Now we define the Constraints on the getter,
because api-platform only allows to define constraints on a getter. Move the example on ContentNode::data to the getter, because then this example was used for all children for the data property instead of the example on the getter.
~~Now the comment for the property still overwrites the comments for the getters, but this is ok as the inheritance is an implementation detail, and must not be exposed in the api.~~ Edit by @BacLuc: This was wrong

closes #3740

### CODE REVIEW

File: api/src/Entity/ContentNode/SingleText.php [hunk 1]
```diff
@@ -58,14 +58,25 @@ class SingleText extends ContentNode {
...
+        $this->data = json_decode(self::DATA_DEFAULT, true);
+    }
+
     /**
      * Holds the actual data of the content node
      * (overridden from abstract class in order to add specific validation).
      */
-    #[ApiProperty(example: ['html' => 'my example text'])]
+    #[ApiProperty(
+        default: self::DATA_DEFAULT,
```
Comment (usu) [inline api/src/Entity/ContentNode/SingleText.php:73]: Does default has any effect at all? I believe to remember that we noticed earlier, that the default property has no effect and hence removed it from our code.

**Review by usu — APPROVED** [review]

File: api/src/Entity/ContentNode/SingleText.php (hunk 1 above)
Comment (BacLuc) [reply api/src/Entity/ContentNode/SingleText.php:73]: It now has an effect.
Without the default here, it uses the value set on the field.
(it seems to detect what is assigned to the field on initialization).
This happens in ContentNode, and is an unusable default for most of the child classes.

File: api/src/Entity/ContentNode.php [hunk 2]
```diff
@@ -92,8 +92,6 @@ abstract class ContentNode extends BaseEntity implements BelongsToContentNodeTre
     /**
      * Holds the actual data of the content node.
      */
```
Comment (carlobeltrame) [inline api/src/Entity/ContentNode.php]: Should we move the comment to the getter as well? This is also displayed in the OpenAPI spec.

**Review by carlobeltrame — APPROVED** [review]

File: api/src/Entity/ContentNode.php (hunk 2 above)
Comment (BacLuc) [reply api/src/Entity/ContentNode.php]: it is also displayed in the OpenApi spec if the comment is on the field.
https://pr3749.ecamp3.ch/api#model-ContentNode.jsonhal-read

Do you suggest 
to add it to the getter too
or move it to the getter?

Comment (carlobeltrame) [reply api/src/Entity/ContentNode.php]: I would move it to the getter, to make it clear to future devs where all the information in the OpenAPI spec comes from

Comment (BacLuc) [reply api/src/Entity/ContentNode.php]: I will try to move it to the getter.

Comment (BacLuc) [reply api/src/Entity/ContentNode.php]: done

**Review by carlobeltrame — APPROVED** [review]
:+1: feel free to merge when you are done force pushing
