### PR TITLE
Replace moment.js with dayjs

### LINKED ISSUE #509: Moment.js empfiehlt nicht mehr Moment zu verwenden
https://momentjs.com/docs/#/-project-status/

### LINKED ISSUE #525: VeeValidate MinDate + German not working
VeeValidate MinDate funktioniert bei Sprache Deutsch nicht.
Grund: new Date('20.11.2020') kann nicht korrekt geparsed werden.

### PR DESCRIPTION
**Pull request by simfeld**
Fixes #509
Fixes #525

### CODE REVIEW

File: frontend/src/App.vue [hunk 1]
```diff
@@ -41,7 +41,7 @@ export default {
     }
   },
   created () {
-    this.$store.commit('setLanguage', this.$store.state.language)
+    this.$store.commit('setLanguage', this.$store.state.lang.language)
```
Comment (simfeld) [inline frontend/src/App.vue:44]: Not related to moment replacement, but did not work before.

File: frontend/src/components/form/base/EDatePicker.vue [hunk 2]
```diff
@@ -55,30 +55,22 @@ export default {
   methods: {
     format (val) {
       if (val !== '') {
-        return this.$moment.utc(val, this.valueFormat, this.$i18n.locale).format('L')
+        return this.$date.utc(val, this.valueFormat).format('L')
```
Comment (simfeld) [inline frontend/src/components/form/base/EDatePicker.vue:58]: It makes no sense to use $i18n.locale explicitly here. The dayjs locale is set globally in `setLanguage`.

File: frontend/src/components/form/base/EDatePicker.vue [hunk 3]
```diff
@@ -55,30 +55,22 @@ export default {
...
       }
       return ''
     },
     parse (val) {
       if (val) {
-        const m = this.$moment.utc(val, 'L', this.$i18n.locale)
-        if (m.isValid()) {
-          return Promise.resolve(m.format(this.valueFormat))
+        const parsedDate = this.$date.utc(val, 'L')
+        if (parsedDate.isValid() && parsedDate.format('L') === val) {
```
Comment (simfeld) [inline frontend/src/components/form/base/EDatePicker.vue:71]: Dayjs only checks if the date can be parsed successfully, but not for the validity of the date (i.e. February 31 or month number 13).

File: frontend/src/components/form/base/EDatePicker.vue [hunk 4]
```diff
@@ -55,30 +55,22 @@ export default {
...
+          return Promise.resolve(parsedDate.format(this.valueFormat))
         } else {
-          switch (m.parsingFlags().overflow) {
```
Comment (simfeld) [inline frontend/src/components/form/base/EDatePicker.vue:74]: Not supported, but I think this is not critical.

File: frontend/src/components/form/base/ETimePicker.vue [hunk 5]
```diff
@@ -57,25 +57,46 @@ export default {
   },
   methods: {
     allowedStep: m => m % 15 === 0,
+    parseTime (value) {
+      if (this.valueFormat === 'x') {
```
Comment (simfeld) [inline frontend/src/components/form/base/ETimePicker.vue:61]: `x` is not directly supported as a format identifier.

File: frontend/src/components/form/base/ETimePicker.vue [hunk 6]
```diff
@@ -85,10 +106,10 @@ export default {
     },
     parsePicker (val) {
       if (val) {
-        const m = this.$moment.utc(val, this.$moment.HTML5_FMT.TIME)
-        this.dateTime.hours(m.hours()).minutes(m.minutes()).seconds(m.seconds()).milliseconds(m.milliseconds())
-        if (m.isValid()) {
-          return Promise.resolve(this.dateTime.format(this.valueFormat))
+        const parsedDateTime = this.$date.utc(val, 'HH:mm')
+        if (parsedDateTime.isValid() && parsedDateTime.format('HH:mm') === val) {
+          this.dateTime = this.setTime(this.dateTime, parsedDateTime)
```
Comment (simfeld) [inline frontend/src/components/form/base/ETimePicker.vue]: Only set the new time if validation was successful.

File: frontend/src/plugins/veeValidate.js [hunk 7]
```diff
@@ -27,7 +27,9 @@ class VeeValidatePlugin {
     extend('minDate', {
       params: ['min'],
       validate: (value, { min }) => {
-        return new Date(value) >= new Date(min)
+        const minDate = Vue.dayjs.utc(min, 'L')
+        const valueDate = Vue.dayjs.utc(value, 'L')
+        return valueDate.diff(minDate, 'day') >= 0
```
Comment (simfeld) [inline frontend/src/plugins/veeValidate.js:32]: This did not work in locale `de` before (and probably all locales except `en`).

File: frontend/src/components/form/base/EDatePicker.vue (hunk 2 above)
Comment (carlobeltrame) [reply frontend/src/components/form/base/EDatePicker.vue:58]: I believe this way necessary in moment.js, but all the better if it's globally configurable in day.js

File: frontend/src/views/Profile.vue [hunk 8]
```diff
@@ -25,7 +25,7 @@
         <api-date-picker
           :name="$tc('entity.user.fields.birthday')"
           :uri="profile._meta.self"
-          :value-format="$moment.HTML5_FMT.DATE"
+          :value-format="'YYYY-MM-DD'"
```
Comment (BacLuc) [inline frontend/src/views/Profile.vue]: A constant for the date format would be nice.
I would add it when we need this literal another time.

File: frontend/src/components/form/base/ETimePicker.vue [hunk 9]
```diff
@@ -57,25 +57,46 @@ export default {
...
     },
     parse (val) {
       if (val) {
-        const m = this.$moment.utc(val, 'LT')
-        this.dateTime.hours(m.hours()).minutes(m.minutes()).seconds(m.seconds()).milliseconds(m.milliseconds())
-        if (m.isValid()) {
-          return Promise.resolve(this.dateTime.format(this.valueFormat))
+        const parsedDateTime = this.$date.utc(val, 'LT')
+        if (parsedDateTime.isValid() && parsedDateTime.format('LT') === val) {
+          this.dateTime = this.setTime(this.dateTime, parsedDateTime)
```
Comment (BacLuc) [inline frontend/src/components/form/base/ETimePicker.vue]: this.setTime throws an NPE if the TimePicker is initialized without a value. (as in /controls).
TypeError: initialDateTime is null
    setTime ETimePicker.vue:75
    parsePicker ETimePicker.vue:111
    inputPicker BasePicker.vue:173
    VueJS 4
    emitValue VTimePicker.ts:198
    onInput VTimePicker.ts:241
    VueJS 4
    update VTimePickerClock.ts:234
    setMouseDownValue VTimePickerClock.ts:229
    onDragMove VTimePickerClock.ts:206
    onMouseDown VTimePickerClock.ts:180
    VueJS 

I would expect that setTime sets the state directly and knows the previous state.
Now the user of setTime (which seems to set the dateTime Object), has to check if this.dateTime is null or not.

Either move the null check into setTime and set the time there,
or rename setTime to createDateTimeFrom.

And because the NPE happened now, a test for empty initialization would be nice.

**Review by BacLuc — CHANGES_REQUESTED** [review]
Danke, scheint fleissarbeit gewesen zu sein.
Technisch schein fast alles direkt funktioniert zu haben.

File: frontend/src/components/form/base/EDatePicker.vue (hunk 2 above)
Comment (simfeld) [reply frontend/src/components/form/base/EDatePicker.vue:58]: Are you sure? https://github.com/ecamp/ecamp3/blob/07a931704b3430d520046616e22bf2811888fc77/frontend/src/components/form/base/ETimePicker.vue#L62-L63 The moment locale was also globally configurable https://github.com/ecamp/ecamp3/blob/57f534f9ea230c67f7955b97d695d387d9878914/frontend/src/plugins/store/lang.js#L21

Comment (carlobeltrame) [reply frontend/src/components/form/base/EDatePicker.vue:58]: :man_shrugging:

File: frontend/src/main.js [hunk 10]
```diff
@@ -1,9 +1,10 @@
 import Vue from 'vue'
 import App from './App.vue'
 import router from '@/router'
-import { vuetifyLoader, auth, storeLoader, filterLoading, formBaseComponents, ignoreNativeBindingWarnMessages, i18n, veeValidate, vueMoment, moment } from './plugins'
+import { vuetifyLoader, auth, storeLoader, filterLoading, formBaseComponents, ignoreNativeBindingWarnMessages, i18n, veeValidate } from './plugins'
 import { store } from './plugins/store'
 import { vuetify } from './plugins/vuetify'
+import './plugins/dayjs'
```
Comment (carlobeltrame) [inline frontend/src/main.js]: Could you wrap the contents of this file in a small plugin, like we already do for e.g. auth? We have previously had issues with import statements with side effects, see https://github.com/ecamp/ecamp3/pull/616#discussion_r522342206.

**Review by BacLuc — APPROVED** [review]
My comments are resolved

File: frontend/src/views/Profile.vue (hunk 8 above)
Comment (BacLuc) [reply frontend/src/views/Profile.vue]: Thank you

**Review by pmattmann — APPROVED** [review]
