### PR TITLE
Fix php function return types

### LINKED ISSUE #838: PHP: Use PHP RFC: Return (PHP 7)
Seit PHP 7 ist der [PHP RFC: Return Type Declarations](https://wiki.php.net/rfc/return_types) implementiert.
Code umbauen von 
```php
/**
 * @return ReturnType
 */
function foo() { ... }
```
auf
```php
function foo(): ReturnType { ... }
```

### PR DESCRIPTION
**Pull request by carlobeltrame**
Fixes #838 

In AuthController and Auth\BaseController, the redirect responses are necessary due to the OAuth protocol. So there, we are not able to return ViewModel. In all other places, we now return ViewModel, and also declare `void` return types. php-cs-fixer made this easy, but we can't permanently activate these rules without enabling risky rules.

### CODE REVIEW

**Comment by pmattmann** [comment]
Können wir bitte vorher #950 mergen?

File: backend/module/eCampApi/src/eCampApi/V1/Rpc/Register/RegisterController.php [hunk 1]
```diff
@@ -15,29 +18,29 @@ public function __construct(RegisterService $registerService) {
...
+            throw new InvalidArgumentException('No email provided');
         }
         if (empty($data->password)) {
-            return new ApiProblem(400, 'No password provided');
+            throw new InvalidArgumentException('No password provided');
         }
         $data->mailAddress = $data->email;
         $user = $this->registerService->register($data);
 
         if ($user instanceof ApiProblem) {
```
Comment (BacLuc) [inline backend/module/eCampApi/src/eCampApi/V1/Rpc/Register/RegisterController.php]: we should throw an exception in the registerService, but we can do that later

File: backend/.php_cs [hunk 2]
```diff
@@ -14,7 +14,8 @@ return PhpCsFixer\Config::create()
         '@DoctrineAnnotation' => true,
         '@PhpCsFixer' => true,
         'braces' => ['position_after_functions_and_oop_constructs' => 'same'],
-        'php_unit_test_class_requires_covers' => false
+        'php_unit_test_class_requires_covers' => false,
+        'no_superfluous_phpdoc_tags' => true,
```
Comment (BacLuc) [inline backend/.php_cs:18]: will you revert the rule in this PR in a follow up commit, or do we merge it?

Comment (carlobeltrame) [reply backend/.php_cs:18]: This one I would merge, because it is not considered risky. If we remove it, cs-fixer will start complaining about now incomplete phpdoc annotations I think.

File: backend/module/eCampApi/src/eCampApi/V1/Rpc/Register/RegisterController.php (hunk 1 above)
Comment (carlobeltrame) [reply backend/module/eCampApi/src/eCampApi/V1/Rpc/Register/RegisterController.php]: Good catch, thanks! Actually, this `if` can never be satisfied, now that `RegisterService#register` is declared to return `User`. I have removed it. The `RegisterService` does throw some exceptions under some circumstances already, such as `NoAccessException` when ACL fails, etc.

**Comment by manuelmeister** [comment]
Ich habe mir noch überlegt, ob wir auch Generics definieren könnten. (Momentan nur via DocBlocks möglich)

Damit wir zB bei den Services nicht immer noch einen "Cast" machen müssen.

**Review by BacLuc — APPROVED** [review]

**Review by pmattmann — APPROVED** [review]
