### PR TITLE
fix(api): properly encode URLs in RelatedCollectionLinkNormalizer

### LINKED ISSUE #2289: Links generated by RelatedCollectionLinkNormalizer are not always urlencoded
RelatedCollectionLinkNormalizer produces inconsistent urlencoding with link parameters.

URIs generated by the following line are not urlencoded:
https://github.com/ecamp/ecamp3/blob/devel/api/src/Serializer/Normalizer/RelatedCollectionLinkNormalizer.php#L164
```php
return $this->router->generate($this->routeNameResolver->getRouteName($relatedResourceClass, OperationType::COLLECTION), [$relatedFilterName => $this->iriConverter->getIriFromItem($object)], UrlGeneratorInterface::ABS_PATH);
```

URIs generated by this line are urlencoded:
https://github.com/ecamp/ecamp3/blob/devel/api/src/Serializer/Normalizer/RelatedCollectionLinkNormalizer.php#L143
```php
return $this->uriTemplate->expand($uriTemplate, $params);
```

We should decide for one. I believe non-encoded is the standard in HAL specification.

### PR DESCRIPTION
**Pull request by usu**
Fixes #2289 

After https://github.com/symfony/symfony/pull/45658 made it into the release of symfony 6.1, we can now properly encode query parameters in `RelatedCollectionLinkNormalizer`

Also tested Frontend side. Everything still working.

### CODE REVIEW

**Review by pmattmann — APPROVED** [review]

File: api/tests/Api/Periods/ReadPeriodTest.php [hunk 1]
```diff
@@ -103,8 +103,8 @@ public function testGetSinglePeriodIsAllowedForManager() {
             '_links' => [
                 'camp' => ['href' => $this->getIriFor('camp1')],
                 'materialItems' => ['href' => '/material_items?period=%2Fperiods%2F'.$period->getId()], // TODO: fix encoding with https://github.com/ecamp/ecamp3/issues/2289
```
Comment (carlobeltrame) [inline api/tests/Api/Periods/ReadPeriodTest.php]: Is this solved now? Can this TODO be removed?

**Review by carlobeltrame — APPROVED** [review]

File: api/tests/Api/Periods/ReadPeriodTest.php (hunk 1 above)
Comment (usu) [reply api/tests/Api/Periods/ReadPeriodTest.php]: Yes, thanks. Removed the comments.
